### PR TITLE
Debian pkg

### PR DESCRIPTION
**Pull request by mnalis**
this pull requests finally clears the issues queue! (although I'll probably add several minor notes there)

- regenerates all remaining binary data files from source
- image conversion tools now handle resolutions less than 320x200 used for various icons/ship parts etc. 
- fix to allow terminating even if video has not been initizalized yet
- allow installing ironseed system wide and related fixes (read-only opening of root-owned files needed)
- IMPORTANT CHANGE: now saves savegames in user home dir (`~/.local/share/ironseed` or `~/.ironseed') !
- create rules for building Debian package via `make deb`
- version updated to fpc 0.2.2

### CODE REVIEW

**Comment by nukebloodaxe** [comment]
Could you remind me what sysset.txt was related to again?

**Comment by nukebloodaxe** [comment]
contacts.dta to keep.c under TEMP?  Just for clarification.

**Comment by nukebloodaxe** [comment]
Awesome patch set, well done!  Only those bits of clarification and we're go.  BTW, I have a tidied copy of the main menu png in Ironseed_py, you may want to grab it as it looks much better after the missing pixels are filled.

**Comment by mnalis** [comment]
Sure - `sysset.txt` contains system x,y,z coordinates and number of planets, which is used by `sysmake.pas` together with `Data_Generators/makedata/names.txt` to generate list of systems used for sector map. It also generates human-readable `Data_Generators/other/sysdata.txt` as one of the outputs. 

Previously `sysset.txt` was missing, and binary-only version `sysset.dta` was used. I created `.txt` version so it can be edited, updated etc. by interested parties.

As for the `contacts.dta` -> `keep.c`, it is an automagic-artefact of `git(1)`. When `git` notices that file with one hash has disappeared, but another with same hash (but different name and/or parent directory) has appeared somewhere else, it concludes that it is the same file which has been renamed/moved. This also happens to work for hash `0000000` - which you get out of 0-length file. 

What I actually did was remove all leftover junk in `TEMP/*` and added 0-byte `keep.c` (same name used by original devels for other directories like `saveX`) so directory won't disappear - as it is needed for build process, running the game in-place without installing, etc. (some file in directory is needed to preserve it, as `git` cannot hold empty directories)

Ironseed_py -  wow! Runs fine through intro and crewgen part. My Intel Quadcore i3-7020U CPU @ 2.30GHz laptop is way too slow, though. But stuff seems to work, impressive! I'll add a few issues there I noticed. Hope the COVID-19 situations calms down soon (and not _ONLY_ so you get more time for Ironseed_py!)

**Review by nukebloodaxe — APPROVED** [review]

**Pull request merged**
